import { ArrowHeadType } from 'react-flow-renderer'

export const removeNodesInitial = [
  {
    id: '1',
    type: 'segment',
    data: { isInitial: true, name: 'Segments', shape: 'circle', iconName: 'segment' },
    position: { x: 250, y: 50 },
  },
  {
    id: 'e1-5',
    source: '1',
    target: '5',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '5',
    type: 'segment',
    data: {
      id: 'e1-999',
      source: '1',
      target: '999',
      data: { edgeLabel: 'yes' },
      name: 'Wait for trigger',
      type: 'wait_for_trigger',
      shape: 'rhomb',
      iconName: 'wait_for_trigger',
    },
    position: { x: 250, y: 220 },
  },
  {
    id: 'e5-6',
    source: '5',
    target: '6',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '6',
    type: 'segment',
    data: {
      id: 'e5-999',
      source: '5',
      target: '999',
      data: { edgeLabel: 'yes' },
      name: 'Time delay',
      type: 'time_delay',
      shape: 'rhomb',
      iconName: 'time_delay',
    },
    position: { x: 250, y: 390 },
  },
  {
    id: 'e6-999',
    source: '6',
    target: '999',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  { id: '999', type: 'end', data: { isFinal: true, name: 'End' }, position: { x: 250, y: 570 } },
]
export const elementsAfterRemoving5 = [
  {
    id: '1',
    type: 'segment',
    data: { isInitial: true, name: 'Segments', shape: 'circle', iconName: 'segment' },
    position: { x: 250, y: 50 },
  },
  {
    id: '6',
    type: 'segment',
    data: {
      id: 'e5-999',
      source: '5',
      target: '999',
      data: { edgeLabel: 'yes' },
      name: 'Time delay',
      type: 'time_delay',
      shape: 'rhomb',
      iconName: 'time_delay',
    },
    position: { x: 250, y: 220 },
  },
  {
    id: '999',
    type: 'end',
    data: { isFinal: true, name: 'End' },
    position: { x: 250, y: 400 },
  },
  {
    id: 'e6-999',
    source: '6',
    target: '999',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: 'arrow',
  },
  {
    id: 'e1-6',
    source: '1',
    target: '6',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: 'arrow',
  },
]
export const neastedBranches = [
  {
    id: '1',
    type: 'segment',
    data: { isInitial: true, name: 'Segments', shape: 'circle', iconName: 'segment' },
    position: { x: 250, y: 50 },
  },
  {
    id: 'e1-5',
    source: '1',
    target: '5',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '5',
    type: 'segment',
    data: {
      id: 'e1-999',
      source: '1',
      target: '999',
      data: { edgeLabel: 'yes' },
      name: 'If / Else',
      type: 'if_else',
      shape: 'rhomb',
      iconName: 'if_else',
    },
    position: { x: 250, y: 220 },
  },
  {
    id: 'e5-11',
    source: '5',
    target: '11',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '11',
    type: 'segment',
    data: {
      id: 'e5-7',
      source: '5',
      target: '7',
      data: { edgeLabel: 'yes' },
      name: 'Wait for trigger',
      type: 'wait_for_trigger',
      shape: 'rhomb',
      iconName: 'wait_for_trigger',
    },
    position: { x: 250, y: 390 },
  },
  {
    id: 'e11-7',
    source: '11',
    target: '7',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '7',
    type: 'segment',
    data: {
      id: 'e5-999',
      source: '5',
      target: '999',
      data: { edgeLabel: 'yes' },
      name: 'If / Else',
      type: 'if_else',
      shape: 'rhomb',
      iconName: 'if_else',
    },
    position: { x: 250, y: 560 },
  },
  {
    id: 'e7-999',
    source: '7',
    target: '999',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  { id: '999', type: 'end', data: { isFinal: true, name: 'End' }, position: { x: 250, y: 740 } },
  { id: '6', type: 'end', data: { isFinal: true, name: 'End' }, position: { x: 570, y: 390 } },
  {
    id: 'e5-6',
    source: '5',
    target: '6',
    type: 'custom',
    sourceHandle: 's-right',
    targetHandle: 't-top',
    data: { edgeLabel: 'no' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  { id: '8', type: 'end', data: { isFinal: true, name: 'End' }, position: { x: 570, y: 1070 } },
  {
    id: 'e7-9',
    source: '7',
    target: '9',
    type: 'custom',
    sourceHandle: 's-right',
    targetHandle: 't-top',
    data: { edgeLabel: 'no' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '9',
    type: 'segment',
    data: {
      id: 'e7-8',
      source: '7',
      target: '8',
      data: { edgeLabel: 'no' },
      name: 'If / Else',
      type: 'if_else',
      shape: 'rhomb',
      iconName: 'if_else',
    },
    position: { x: 570, y: 730 },
  },
  {
    id: 'e9-12',
    source: '9',
    target: '12',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  {
    id: '12',
    type: 'segment',
    data: {
      id: 'e9-8',
      source: '9',
      target: '8',
      data: { edgeLabel: 'yes' },
      name: 'Time delay',
      type: 'time_delay',
      shape: 'rhomb',
      iconName: 'time_delay',
    },
    position: { x: 570, y: 900 },
  },
  {
    id: 'e12-8',
    source: '12',
    target: '8',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
  { id: '10', type: 'end', data: { isFinal: true, name: 'End' }, position: { x: 890, y: 900 } },
  {
    id: 'e9-10',
    source: '9',
    target: '10',
    type: 'custom',
    sourceHandle: 's-right',
    targetHandle: 't-top',
    data: { edgeLabel: 'no' },
    arrowHeadType: ArrowHeadType.Arrow,
  },
]
export const neastedBranchesAfterRemoveFirstBranch = [
  {
    id: '1',
    type: 'segment',
    data: { isInitial: true, name: 'Segments', shape: 'circle', iconName: 'segment' },
    position: { x: 250, y: 50 },
  },
  {
    id: '999',
    type: 'end',
    data: { isFinal: true, name: 'End' },
    position: { x: 250, y: 230 },
  },
  {
    id: 'e1-999',
    source: '1',
    target: '999',
    type: 'custom',
    sourceHandle: 's-bottom',
    targetHandle: 't-top',
    data: { edgeLabel: 'yes' },
    arrowHeadType: 'arrow',
  },
]
